services:
  db:
    image: mysql:8.0.42
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --authentication_policy=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ebdb
    volumes:
      - php-ddd-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - php-ddd
  mail:
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - "1080:8025"
    networks:
      - php-ddd
  redis:
    image: redis:7.4.2
    networks:
      - php-ddd
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./fuelphp/docker/localhost
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./fuelphp/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./fuelphp/docker/localhost/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./fuelphp/public:/app/fuelphp/public
    networks:
      - php-ddd
    depends_on:
      - fuelphp
  fuelphp:
    build:
      context: ./fuelphp/docker
      dockerfile: localhost/php.dockerfile
    environment:
      FUEL_ENV: development
      APP_URL: http://localhost:8080/
      PHP_MEMORY_LIMIT: 256M
      APP_CIPHER_KEY: 8218bc92e8f238e544019f211de3e7f6c143d781b3e25f0f35863833f371f9d9
      APP_TOKEN_SALT: R2AvvgZcNEmmY6wbhPBMma4amsdUvHnLWvijER3a

      # MySQL config
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_DB_NAME: ebdb
      DB_USERNAME: root
      DB_PASSWORD: root

      # Redis config
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # IDE config
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./backend:/app/backend
      - ./fuelphp:/app/fuelphp
    networks:
      - php-ddd
    depends_on:
      - redis
      - db
      - mail

networks:
  php-ddd:
    driver: bridge

volumes:
  php-ddd-db:
